import LiftCharts from "./components/LiftCharts";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

async function getDailyUpdate() {
  try {
    const update = await prisma.dailyUpdate.findFirst({
      orderBy: { generatedAt: "desc" },
    });
    if (!update) {
      return { content: "No update yet. Get in the gym.", generatedAt: null };
    }
    return { content: update.content, generatedAt: update.generatedAt.toISOString() };
  } catch {
    return { content: "No update yet. Get in the gym.", generatedAt: null };
  }
}

export default async function Home() {
  const session = await getServerSession(authOptions);
  const dailyUpdate = await getDailyUpdate();

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="space-y-8">
      {/* Daily Squanch Update */}
      <div className="bg-neutral-900 rounded-xl p-6 border border-amber-600/40 shadow-lg shadow-amber-900/10">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-bold text-amber-400">📰 Daily Squanch Update</h2>
          <span className="text-sm text-neutral-500">{today}</span>
        </div>
        <p
          className="text-neutral-200 leading-relaxed whitespace-pre-wrap"
          style={{ whiteSpace: "pre-wrap" }}
        >
          {dailyUpdate.content}
        </p>
        <p className="mt-4 text-xs text-neutral-600 text-right">Generated by Bung 🐡</p>
      </div>

      {!session && (
        <div className="bg-neutral-900 rounded-xl p-6 border border-neutral-800 text-center">
          <p className="text-neutral-300">
            <a href="/login" className="text-blue-400 hover:underline font-medium">
              Log in
            </a>{" "}
            to add your lifts
          </p>
        </div>
      )}
      <LiftCharts />
    </div>
  );
}
